services:
  # Contao frontend module "calendar_event_booking_member_list_module"
  markocupic.calendar_event_booking_frontend_bundle.controller.frontend_module.calendar_event_booking_member_list_controller:
    class: Markocupic\CalendarEventBookingFrontendBundle\Controller\FrontendModule\CalendarEventBookingMemberListController
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@contao.routing.scope_matcher'
    - '@database_connection'
    tags:
    - { name: contao.frontend_module, category: events }
    public: true

  # Contao dca class
  markocupic.calendar_event_booking_frontend_bundle.contao.dca.tl_module:
    class: Markocupic\CalendarEventBookingFrontendBundle\Contao\Dca\TlModule
    arguments:
    - '@contao.framework'
    - '@database_connection'
    - '%kernel.project_dir%'
    - '@security.helper'
    - '@request_stack'
    - '@contao.routing.scope_matcher'
    public: true

